name: Download and get info about boot.img

on:
  workflow_dispatch:
    inputs:
      link: 
        description: archive name for download
        type: string
        required: true
      debug:
        description: Enable debug mode?
        type: boolean
env:
  GH_TOKEN: ''
    
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download factory
        run: |
          wget --progress=dot:mega https://dl.google.com/developers/android/cinnamonbun/images/factory/${{ inputs.link }}

      - name: Unpack boot.img from downloaded file
        run: |
          unzip ${{ inputs.link }} -d temp
          unzip $(find "$PWD/temp" -type f -name '*.zip') boot.img -d .
      - name: Download tools
        run: |
          gh release download https://github.com/topjohnwu/Magisk
          
      - name: Debbug VS Code
        if: always() && inputs.debug
        uses: fawazahmed0/action-debug-vscode@main
